### ISSUE TITLE
Fixa en basic html sida som visar olika repos

### ISSUE THREAD

**Issue by nybergjack** [djnoodle/iths-komplettering#3]
# Fixa basic html sida
### Tasks
- [ ] Installera vue vite (https://vitejs.dev/guide/)
- [ ] Insallera axios
- [ ] Hämta olika städer från denna apin (https://avancera.app/cities/)
- [ ] Visa upp städerna med v-for
- [ ]  Lägg till css

**Comment by nybergjack** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [hej](https://trello.com/c/ePB1lVrj/1-hej)

**Comment by nybergjack** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Målet](https://trello.com/c/ePB1lVrj/1-m%C3%A5let)

**Comment by nybergjack** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fixa en basic html sida som visar olika repos](https://trello.com/c/73i2k18g/2-fixa-en-basic-html-sida-som-visar-olika-repos)

**Comment by nybergjack** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fixa en basic html sida som visar olika repos](https://trello.com/c/73i2k18g/2-fixa-en-basic-html-sida-som-visar-olika-repos)
